CREATE TABLE tasks (
    id UUID PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    time TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    status VARCHAR(20) CHECK (status IN ('PENDING', 'STARTED', 'DONE')) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NULL
);